#!/usr/bin/php
<?php

// Set number of servers to build
$num_servers = "3";

// Set server name prefix
$name_prefix = "web";

// Callback function for WaitFor
function progress($server) {
    printf("%s:%-8s %3d%% complete\r",
        $server->name, $server->status, $server->progress);
}

// Include necessary libraries
require('rackspace.php');

// Get credentials and configuration from ~/.rackspace_cloud_credentials
$inifile = $_SERVER['HOME'] . "/.rackspace_cloud_credentials";
define('INIFILE', $inifile);
$ini = parse_ini_file(INIFILE, TRUE);
if (!$ini) {
    printf("Unable to load .ini file [%s]\n", INIFILE);
    exit;
}

// Authenticate
print "Authenticating...\n";
$conn = new OpenCloud\Rackspace(
     $ini['Identity']['url'],
     array(
         'username' => $ini['Identity']['username'],
         'tenantName' => $ini['Identity']['tenant'],
         'apiKey' => $ini['Identity']['apiKey']
     ));

// Create objects
$compute = $conn->Compute($ini['Compute']['serviceName'], $ini['Compute']['region']);
$server = $compute->Server();

// Loop and create servers
print "Creating the servers...\n";
for ($i=1; $i<=$num_servers; $i++) {
	$servername = $name_prefix . $i;
	$server->Create(array(
    	'name' => $servername,
    	'flavor' => $compute->Flavor(2),
    	'image' => $compute->ImageList(TRUE,array('name'=>'CentOS 6.3'))->Next()
    	));
	$server->WaitFor('ACTIVE', 300, 'progress');
	print "\nDone\n";
	//Pause 10 seconds to allow metadata to catch up
	sleep(10);
	print $servername . " Info\n";
	print "IP Address: " . $server->accessIPv4 . "\n";
	print "Root Password: " . $server->adminPass . "\n";
}
