#!/usr/bin/php
<?php
// (c)2012 Rackspace Hosting. See COPYING for license.
// This script will create a user specified number of CentOS 6.3 servers in the data center as configured in auth.ini

require('rackspace.inc');

// Get credentials and configuration from auth.ini
define('INIFILE', 'auth.ini');
$ini = parse_ini_file(INIFILE, TRUE);
if (!$ini) {
    printf("Unable to load .ini file [%s]\n", INIFILE);
    exit;
}

// Set number of servers to build
$num_servers = "3";

// Set server name prefix
$name_prefix = "web";

//Authenticate
print "Authenticating...\n";
$conn = new OpenCloud\Rackspace(
     $ini['Identity']['url'],
     array(
         'username' => $ini['Identity']['username'],
         'tenantName' => $ini['Identity']['tenant'],
         'apiKey' => $ini['Identity']['apiKey']
     ));

//Create objects
$compute = $conn->Compute($ini['Compute']['serviceName'], $ini['Compute']['region']);
$server = $compute->Server();

//Create servers
print "Creating the servers...\n";
for ($i=1; $i<=$num_servers; $i++) {
	$servername = $name_prefix . $i;
	$server->Create(array(
    	'name' => $servername,
    	'flavor' => $compute->Flavor(2),
    	'image' => $compute->ImageList(TRUE,array('name'=>'CentOS 6.3'))->Next()
    	));
	$server->WaitFor('ACTIVE', 300, 'progress');
	print "\nDone\n";
	print $servername . " Info\n";
	print "IP Address: " . $server->accessIPv4 . "\n";
	print "Root Password: " . $server->adminPass . "\n";
}

// callback function for WaitFor
function progress($server) {
    printf("%s:%-8s %3d%% complete\r",
        $server->name, $server->status, $server->progress);
}
